server:
  servlet:
    session:
      timeout: 604800
logging:
  level:
    org:
      atmosphere: warn
spring:
  mustache:
    check-template-location: false
  messages:
    basename: messages
    encoding: UTF-8
    cache-duration: -1
    fallback-to-system-locale: false
  #hazelcast:
  # config: classpath:hazelcast-client.yml
vaadin:
  allowed-packages: com.vaadin
telegram:
  bot:
    token: ${TELEGRAM_BOT_TOKEN}
app:
  host: localhost
  grpc:
    services:
      player:
        port: 9091