server:
  servlet:
    session:
      timeout: 604800
logging:
  level:
    org.atmosphere: WARN
    org.apache.kafka.clients.consumer.ConsumerConfig: WARN
    org.apache.kafka.clients.producer.ProducerConfig: WARN
    io.confluent.kafka.serializers.KafkaAvroDeserializerConfig: WARN
    io.confluent.kafka.serializers.KafkaAvroSerializerConfig: WARN
spring:
  mustache:
    check-template-location: false
  messages:
    basename: messages
    encoding: UTF-8
    cache-duration: -1
    fallback-to-system-locale: false
  #hazelcast:
  # config: classpath:hazelcast-client.yml
  kafka:
    bootstrap-servers: ${SERVER_HOST}:9092
    properties:
      schema.registry.url: http://${SERVER_HOST}:8081
vaadin:
  allowed-packages: com.vaadin
telegram:
  bot:
    token: ${TELEGRAM_BOT_TOKEN}
app:
  host: localhost
  grpc:
    services:
      player:
        port: 9091
management:
  endpoints:
    web:
      exposure:
        include: "*"