spring:
  application:
    name: solo-leveling-ui
  mustache:
    check-template-location: false
  messages:
    basename: messages
    encoding: UTF-8
    cache-duration: -1
    fallback-to-system-locale: false
  #hazelcast:
  # config: classpath:hazelcast-client.yml
  kafka:
    bootstrap-servers: localhost:9092
    properties:
      schema.registry.url: http://localhost:8081
vaadin:
  allowed-packages: com.vaadin
app:
  grpc:
    services:
      player:
        host: localhost
        port: 9090
  telegram:
    bot:
      token: ${TELEGRAM_BOT_TOKEN_DEV}
management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  port: 8089
  servlet:
    session:
      timeout: 604800
logging:
  level:
    org.atmosphere: WARN
    org.apache.kafka.clients.consumer.ConsumerConfig: WARN
    org.apache.kafka.clients.producer.ProducerConfig: WARN
    io.confluent.kafka.serializers.KafkaAvroDeserializerConfig: WARN
    io.confluent.kafka.serializers.KafkaAvroSerializerConfig: WARN