apiVersion: apps/v1
kind: Deployment
metadata:
  name: solo-leveling-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: solo-leveling-gateway
  template:
    metadata:
      labels:
        app: solo-leveling-gateway
      annotations:
        commit.sha: "${DEPLOY_IMAGE}"
    spec:
      containers:
        - name: app
          image: $DEPLOY_IMAGE
          ports:
            - containerPort: 8080
          env:
            - name: TELEGRAM_BOT_TOKEN_APP
              value: "${TELEGRAM_BOT_TOKEN_APP}"
            - name: JWT_SECRET
              value: "${JWT_SECRET}"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5