apiVersion: apps/v1
kind: Deployment
metadata:
  name: solo-leveling-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: solo-leveling-ui
  template:
    metadata:
      labels:
        app: solo-leveling-ui
      annotations:
        commit.sha: "${GIT_COMMIT_SHA}"
    spec:
      containers:
        - name: app
          image: $DOCKERHUB_USER/solo-leveling-ui:$GIT_COMMIT_SHA
          ports:
            - containerPort: 8080
          env:
            - name: SERVER_HOST
              value: "${SERVER_HOST}"
            - name: TELEGRAM_BOT_TOKEN
              value: "${TELEGRAM_BOT_TOKEN}"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5