spring:
  data:
    redis:
      host: redis
  rabbitmq:
    host: rabbitmq
app:
  grpc:
    services:
      player:
        host: soloist-player
        port: 90
      media:
        host: soloist-media
        port: 90
  telegram:
    bot:
      token: ${TELEGRAM_BOT_TOKEN_APP}
  rabbitmq:
    stomp:
      host: rabbitmq
server:
  port: 8080