openapi: 3.0.3
info:
  title: Solo leveling gateway websocket
  version: 1.0.0

components:
  schemas:
    Message:
      type: object
      properties:
        payload:
          $ref: '#/components/schemas/Notification'
        timestamp:
          type: string
          format: date-time
      required:
        - payload
        - timestamp

    Notification:
      type: object
      properties:
        message:
          type: string
        type:
          $ref: '#/components/schemas/NotificationType'
        source:
          $ref: '#/components/schemas/NotificationSource'
        visible:
          type: boolean
      required:
        - type
        - source
        - visible

    NotificationType:
      type: string
      enum: [ info, warning, error ]

    NotificationSource:
      type: string
      enum: [ tasks ]